package com.housingplatform.shared.service;

import com.housingplatform.shared.dto.DisplaySettingsResponse;
import com.housingplatform.shared.dto.DisplaySettingsUpdateRequest;

public interface DisplaySettingsService {

  String KEY_SPONSOR_CAROUSEL_AUTOPLAY_MS = "SPONSOR_CAROUSEL_AUTOPLAY_MS";
  String KEY_SIDEBAR_MEDIA_ROTATION_MS = "SIDEBAR_MEDIA_ROTATION_MS";
  String KEY_SIDEBAR_LAYOUT_ROTATION_MS = "SIDEBAR_LAYOUT_ROTATION_MS";

  String KEY_EXHIBITION_SPONSORSHIP_PACKAGES_VISIBLE = "EXHIBITION_SPONSORSHIP_PACKAGES_VISIBLE";

  String KEY_EXHIBITION_SPONSORSHIP_PACKAGE_PRICES_VISIBLE =
      "EXHIBITION_SPONSORSHIP_PACKAGE_PRICES_VISIBLE";

  String KEY_EXHIBITION_LIVE_VISIBLE = "EXHIBITION_LIVE_VISIBLE";
  String KEY_LIVE_SOURCE_TYPE = "LIVE_SOURCE_TYPE";
  String KEY_LIVE_EMBED_URL = "LIVE_EMBED_URL";
  String KEY_LIVE_HLS_URL = "LIVE_HLS_URL";
  String KEY_LIVE_TITLE = "LIVE_TITLE";
  String KEY_LIVE_YOUTUBE_URL = "LIVE_YOUTUBE_URL";
  String KEY_LIVE_TIKTOK_URL = "LIVE_TIKTOK_URL";
  String KEY_LIVE_FACEBOOK_URL = "LIVE_FACEBOOK_URL";
  String KEY_EXHIBITION_LIVE_AUTO_SIMULCAST = "EXHIBITION_LIVE_AUTO_SIMULCAST";

  String KEY_EXHIBITION_FEEDBACK_VISIBLE = "EXHIBITION_FEEDBACK_VISIBLE";
  String KEY_EXHIBITION_FEEDBACK_AUTO_PUBLISH = "EXHIBITION_FEEDBACK_AUTO_PUBLISH";

  /** Registration number of the organization that supplies the public footer contact block. */
  String KEY_FOOTER_ORGANIZATION_REGISTRATION_NUMBER = "FOOTER_ORGANIZATION_REGISTRATION_NUMBER";

  DisplaySettingsResponse getDisplaySettings();

  DisplaySettingsResponse updateDisplaySettings(DisplaySettingsUpdateRequest request);
}
